README.md

Updating link for the BasicWearMap, Looks like link has changed and right now it goes to 404 page,
I believe the new link should point to https://github.com/googlemaps/android-samples/tree/master/AndroidWearMap

Updating link for the BasicWearMap

---

AndroidWearMap/README.md
ApiDemos/README.md
README.md

Now, these options (to clone a repository or download an archived snapshot) are at the top of page, because [Github changed the repositories' layout](https://github.com/blog/2085-a-new-look-for-repositories).

Updated information about the place to clone this repository or to download an archived snapshot.

---

README.md

Adds a CI badge to the README file that links to the GitHub CI builds:

docs: Add CI badge to README

---

ApiDemos/kotlin/app/build.gradle
ApiDemos/kotlin/app/src/main/java/com/example/kotlindemos/BasicMapDemoActivity.kt

This pull request reverts https://github.com/googlemaps/android-samples/pull/193 and https://github.com/googlemaps/android-samples/pull/188 to remove KTX from the basic map demo.
Per further discussion we're going to have these samples be pure Kotlin implementations without KTX.

chore: Remove KTX from basic map demo

---

tutorials/java/MapWithMarker/app/src/main/java/com/example/mapwithmarker/MapsMarkerActivity.java
tutorials/java/Polygons/app/src/main/java/com/example/polygons/PolyActivity.java
tutorials/kotlin/Polygons/app/src/main/java/com/example/polygons/PolyActivity.kt

[END_EXCLUDE] w/o `silent` is the proper way to escape [START_EXCLUDE silent]

chore: Remove 'silent' from END_EXCLUDE tags

---

ApiDemos/java/app/build.gradle
ApiDemos/java/app/src/gms/java/com/example/mapdemo/BasicMapDemoActivity.java
ApiDemos/java/app/src/gms/java/com/example/mapdemo/DemoDetailsList.java
ApiDemos/java/app/src/gms/java/com/example/mapdemo/polyline/PolylineDemoActivity.java
ApiDemos/java/app/src/main/AndroidManifest.xml
ApiDemos/kotlin/app/build.gradle
ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/LiteListDemoActivity.kt
ApiDemos/kotlin/app/src/main/AndroidManifest.xml
ApiDemos/kotlin/app/src/v3/java/com/example/kotlindemos/LiteListDemoActivity.kt

Updates target SDK version to API level 30. Other changes:
* explicit query to open Google Maps app. This is necessary so that buttons on the [map toolbar UI](https://developers.google.com/maps/documentation/android-sdk/controls) work. Otherwise, an error saying 'Google Maps is not installed or is disabled' will appear as pointed out in #371. This change is necessary as per package visibility changes introduced in Android 11.
* Fix `AndroidManifest.xml` reference to `PolylineDemoActivity` for the `gmsDebug` gradle variant.
Fixes #371 🦕

feat: Target API level 30.

---

ApiDemos/java/app/src/main/AndroidManifest.xml
ApiDemos/kotlin/app/src/main/AndroidManifest.xml

Removing queries entry as this is no longer needed in version 17.0.1. See [release notes](https://developers.google.com/maps/documentation/android-sdk/releases#april_27_2021).

chore: Remove queries entry.

---

ApiDemos/java/app/build.gradle
ApiDemos/java/build.gradle
ApiDemos/kotlin/app/build.gradle
ApiDemos/kotlin/build.gradle
snippets/app/build.gradle
snippets/build.gradle
tutorials/java/CurrentPlaceDetailsOnMap/app/build.gradle
tutorials/java/CurrentPlaceDetailsOnMap/build.gradle
tutorials/java/MapWithMarker/app/build.gradle
tutorials/java/MapWithMarker/build.gradle
tutorials/java/Polygons/app/build.gradle
tutorials/java/Polygons/build.gradle
tutorials/java/StyledMap/build.gradle
tutorials/kotlin/CurrentPlaceDetailsOnMap/app/build.gradle
tutorials/kotlin/CurrentPlaceDetailsOnMap/build.gradle
tutorials/kotlin/MapWithMarker/app/build.gradle
tutorials/kotlin/MapWithMarker/build.gradle
tutorials/kotlin/Polygons/app/build.gradle
tutorials/kotlin/Polygons/build.gradle

Update to secrets-gradle-plugin 1.2.0 which has a new maven coordinate located with google maven. See the secrets-gradle-plugin [README](https://github.com/google/secrets-gradle-plugin#installation) installation instructions to learn more.

chore: Update to secrets-gradle-plugin 1.2.0

---

WearOS/Wearable/build.gradle
WearOS/Wearable/src/main/AndroidManifest.xml
tutorials/java/Polygons/app/src/main/java/com/example/polygons/PolyActivity.java
tutorials/kotlin/Polygons/app/src/main/java/com/example/polygons/PolyActivity.kt

The previous color names did not match the actual color values.

fix: Fix color names.

---

ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/CameraDemoActivity.kt

map object was not initialized, and it caused a crash in the sample app. Logs in #795

fix: force close in the camera demo activity

---

ApiDemos/java/gradle/wrapper/gradle-wrapper.properties
ApiDemos/kotlin/gradle/wrapper/gradle-wrapper.properties

chore: Use Gradle 7.2 in ApiDemos

---

ApiDemos/kotlin/app/build.gradle
ApiDemos/kotlin/build.gradle
WearOS/Wearable/build.gradle
WearOS/build.gradle
snippets/app/build.gradle
snippets/build.gradle
tutorials/kotlin/CurrentPlaceDetailsOnMap/app/build.gradle
tutorials/kotlin/CurrentPlaceDetailsOnMap/build.gradle
tutorials/kotlin/MapWithMarker/build.gradle
tutorials/kotlin/Polygons/build.gradle

Reverting dependencies back to https://github.com/googlemaps/android-samples/commit/0ec4153b3766bc2fcecb0e2b638971544325aa87 from earlier April.

fix: revert dependencies to last green build

---

.github/workflows/build.yml

This adds a summary status check that can be used as required branch protection rule.

build: add test status check

---

snippets/app/build.gradle

As discussed in https://github.com/googlemaps/android-maps-compose/pull/148#issuecomment-1156791458, this PR migrates the region tags for the maps-compose library version from the demo app in that repo to the snippets app in this repo.
---

chore: Add maps-compose library region tags

---

ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/OnMapAndViewReadyListener.kt

The current NPE fixes an NPE that can potentially happen in any Activity using OnMapAndViewReadyListener
Fixes #505 🦕

fix: fixed NPE on OnMapAndViewReadyListener

---

snippets/app/build.gradle

Make the Secrets Gradle Plugin config snippet compatible with both Groovy and Kotlin build scripts by encasing strings in double quotes and only using single quotes for string interpolation.

chore: update build.gradle

---

ApiDemos/java/app/build.gradle
ApiDemos/java/app/src/gms/java/com/example/mapdemo/BasicMapDemoActivity.java
ApiDemos/java/gradle/wrapper/gradle-wrapper.properties
ApiDemos/kotlin/app/build.gradle
ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/BasicMapDemoActivity.kt
ApiDemos/kotlin/gradle/wrapper/gradle-wrapper.properties
WearOS/gradle/wrapper/gradle-wrapper.properties
snippets/gradle/wrapper/gradle-wrapper.properties
tutorials/java/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties
tutorials/java/MapWithMarker/gradle/wrapper/gradle-wrapper.properties
tutorials/java/Polygons/gradle/wrapper/gradle-wrapper.properties
tutorials/java/StyledMap/gradle/wrapper/gradle-wrapper.properties
tutorials/kotlin/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties
tutorials/kotlin/MapWithMarker/gradle/wrapper/gradle-wrapper.properties
tutorials/kotlin/Polygons/gradle/wrapper/gradle-wrapper.properties

Add a region tag to support new code samples on developers.google.com
Upgrade gradle from 8.0 to 8.4 for all apps

chore: add region tag to basic map demo and upgrade gradle

---

ApiDemos/java/gradle/wrapper/gradle-wrapper.properties
ApiDemos/kotlin/gradle/wrapper/gradle-wrapper.properties
hooks/pre-commit
tutorials/java/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties
tutorials/java/MapWithMarker/gradle/wrapper/gradle-wrapper.properties
tutorials/java/Polygons/gradle/wrapper/gradle-wrapper.properties
tutorials/kotlin/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties
tutorials/kotlin/MapWithMarker/gradle/wrapper/gradle-wrapper.properties
tutorials/kotlin/Polygons/gradle/wrapper/gradle-wrapper.properties

This PR improves the sample git hook to prevent a Google API Key from being committed.
The following paper describes the Google API Key Regex structure: https://www.ndss-symposium.org/wp-content/uploads/2019/02/ndss2019_04B-3_Meli_paper.pdf

chore: improved git hook to add Google API Keys

---

ApiDemos/java/app/build.gradle
ApiDemos/java/build.gradle
ApiDemos/java/gradle/wrapper/gradle-wrapper.properties
ApiDemos/kotlin/app/build.gradle
ApiDemos/kotlin/gradle/wrapper/gradle-wrapper.properties
WearOS/gradle/wrapper/gradle-wrapper.properties
snippets/app-compose/build.gradle
snippets/gradle/wrapper/gradle-wrapper.properties
tutorials/java/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties
tutorials/java/MapWithMarker/app/build.gradle
tutorials/java/MapWithMarker/gradle/wrapper/gradle-wrapper.properties
tutorials/java/Polygons/app/build.gradle
tutorials/java/Polygons/build.gradle
tutorials/java/Polygons/gradle/wrapper/gradle-wrapper.properties
tutorials/java/StyledMap/app/build.gradle
tutorials/java/StyledMap/gradle/wrapper/gradle-wrapper.properties
tutorials/kotlin/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties
tutorials/kotlin/MapWithMarker/app/build.gradle
tutorials/kotlin/MapWithMarker/gradle/wrapper/gradle-wrapper.properties
tutorials/kotlin/Polygons/gradle/wrapper/gradle-wrapper.properties

The following PR fixes the builds, after the dependabot PRs that were automatically merged and introduce a compilation issue due to a misalignment on the AGP version.

chore: fixed build after the dependabot updates

---

ApiDemos/java/app/build.gradle
ApiDemos/kotlin/app/build.gradle
README.md
WearOS/README.md
WearOS/build.gradle
docs/GET_AN_API_KEY.md
snippets/app-compose/build.gradle
snippets/app-ktx/build.gradle
snippets/app-places-ktx/build.gradle
snippets/app-rx/build.gradle
snippets/app-utils-ktx/build.gradle
snippets/app-utils/build.gradle
snippets/app/build.gradle
tutorials/java/CurrentPlaceDetailsOnMap/README.md
tutorials/java/MapWithMarker/README.md
tutorials/java/Polygons/README.md
tutorials/java/StyledMap/README.md
tutorials/kotlin/CurrentPlaceDetailsOnMap/README.md
tutorials/kotlin/MapWithMarker/README.md
tutorials/kotlin/Polygons/README.md

Given new best practice to use secrets.properties instead of local.properties with Secrets Gradle Plugin, update related READMEs.

chore: update all instructions to use secrets.properties

---

.github/workflows/build.yml
.github/workflows/release.yml
.releaserc

The following PR fixes the release step.
Since we recently migrated our Groovy Gradle files to Kotlin, the .releaserc file also needs to be updated to reflect the new path. Otherwise [subsequent releases will fail](https://github.com/googlemaps-samples/android-samples/actions/runs/10517638741/job/29142120467).

fix: fixed release step

---

snippets/app-compose/src/main/java/com/example/app_compose/MapsCompose.kt

This PR updates the usage example of `MarkerState()`, passing instead a `rememberMarkerState`.

fix: using rememberMarkerState instead of MarkerState

---

snippets/app-compose/src/main/java/com/example/app_compose/MapsCompose.kt

Fixes broken marker in MapCompose snippet

fix: import rememberMarkerState and use the marker state correctly

---

tutorials/java/CurrentPlaceDetailsOnMap/app/src/main/java/com/example/currentplacedetailsonmap/MapsActivityCurrentPlace.java

The code was repeatedly requesting the access fine location permission in an infinite recursion loop which resulted in the app crashing.  This removes the unnecessary call to request the permission in the updateLocationUI method.

fix: prevents infinite recursion when getting the location permission

---

open-in-idx-template/idx-template.nix

Update idx template to read local.defaults.properties and generate key entries in secrets.properties file using the user's provided API key.

fix: add dynamic key values to secrets.properties in idx template

---

open-in-idx-template/idx-template.nix

fix: remove newline from while loop comment to prevent template error.
Remove unintended newline in comment that caused bash to evaluate the file name as a command.

Cean sandbox

---

open-in-idx-template/devNix.j2

* IDX emulator implementation was change to localhost:5555

fix: Update emulator host in dev.nix for IDX

---

ApiDemos/kotlin/app/src/main/java/com/example/kotlindemos/DemoDetailsList.kt

Re-add MarkerDemoActivity that was accidentally removed in https://github.com/googlemaps-samples/android-samples/commit/429748845447201869a02cf8888881a6142a0d6a

fix: Re-add MarkerDemoActivity in Kotlin sample

---

ApiDemos/java/app/src/main/java/com/example/mapdemo/TileCoordinateDemoActivity.java
ApiDemos/java/app/src/v3/java/com/example/mapdemo/TileCoordinateDemoActivity.java
ApiDemos/kotlin/app/src/main/java/com/example/kotlindemos/TileCoordinateDemoActivity.kt

Bitmaps stored by this provider cause memory leaks after the map is destroyed. Narrowing the scope to a field allows it to be garbage collected and does not affect the provider/activity's ability to serve and render the custom tiles.

fix: stop memory leak in CoordTileProvider

---

.github/dependabot.yml
.github/workflows/release.yml
.releaserc
ApiDemos/project/README.md
ApiDemos/project/common-ui/build.gradle.kts

The following [PR introduced ](https://github.com/googlemaps-samples/android-samples/pull/2026)a unified project for the Kotlin and Java samples. This PR fixes some paths to generate the samples, since now the location has changed.

chore: fixed paths

---

snippets/app-compose/build.gradle.kts
snippets/app-compose/src/main/java/com/example/app_compose/MapsCompose.kt
snippets/app-rx/build.gradle.kts
snippets/app-utils/build.gradle.kts
snippets/app/build.gradle.kts
snippets/gradle/libs.versions.toml
snippets/gradle/wrapper/gradle-wrapper.properties

The following PR updates the dependencies on the snippets. rememberMarkerState was [deprecated](https://github.com/googlemaps/android-maps-compose/pull/730) in favour of rememberUpdatedMarkerState, and this is also reflected now in the snippets.

chore: increased libraries, replaced deprecated methods
