googlemaps-samples/android-samples

ApiDemos/java/app/build.gradle, ApiDemos/java/app/src/main/java/com/example/mapdemo/LiteListDemoActivity.java, ApiDemos/java/app/src/main/res/layout/lite_list_demo_row.xml, ApiDemos/java/app/src/main/res/menu/lite_list_menu.xml, ApiDemos/java/app/src/main/res/values/strings.xml, ApiDemos/java/gradle/wrapper/gradle-wrapper.properties
This pull request is to update the LiteListDemo to use RecyclerView instead of ListView, as requested in #41
=> Changed the LiteListDemo to use RecyclerView

ApiDemos/kotlin/app/src/main/java/com/example/kotlindemos/CameraDemoActivity.kt, ApiDemos/kotlin/app/src/main/java/com/example/kotlindemos/LayersDemoActivity.kt, ApiDemos/kotlin/app/src/main/java/com/example/kotlindemos/MarkerDemoActivity.kt, ApiDemos/kotlin/app/src/main/java/com/example/kotlindemos/OnMapAndViewReadyListener.kt, ApiDemos/kotlin/app/src/main/java/com/example/kotlindemos/PolylineDemoActivity.kt, ApiDemos/kotlin/app/src/main/java/com/example/kotlindemos/TagsDemoActivity.kt
Pull request to address comments from previous pull request (#87) that added Kotlin samples.
=> addresses comments from #87

tutorials/CurrentPlaceDetailsOnMap/app/src/main/AndroidManifest.xml, tutorials/CurrentPlaceDetailsOnMap/app/src/main/java/com/example/currentplacedetailsonmap/MapsActivityCurrentPlace.java
1. Add some check for instance of GoogleMap and result of tasks to prevent NullPointerException
2. Always check permission before use location related functions to prevent LastLocation from null
=> [CurrentPlaceDetailOnMap] Adjust permission request flow and fix some null issues

README.md
Thank you for opening a Pull Request!
---
Fixes #<issue_number_goes_here> 🦕
=> docs: minor typo correction in README.MD

ApiDemos/kotlin/app/src/main/res/layout/activity_main.xml, ApiDemos/kotlin/build.gradle, ApiDemos/kotlin/gradle/wrapper/gradle-wrapper.properties, tutorials/CurrentPlaceDetailsOnMap/build.gradle, tutorials/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties, tutorials/MapWithMarker/build.gradle, tutorials/MapWithMarker/gradle.properties, tutorials/MapWithMarker/gradle/wrapper/gradle-wrapper.properties, tutorials/Polygons/build.gradle, tutorials/Polygons/gradle.properties, tutorials/Polygons/gradle/wrapper/gradle-wrapper.properties, tutorials/StyledMap/build.gradle, tutorials/StyledMap/gradle.properties, tutorials/StyledMap/gradle/wrapper/gradle-wrapper.properties
=> chore(deps): Update to gradle 3.6.2

ApiDemos/kotlin/app/build.gradle, ApiDemos/kotlin/app/src/main/java/com/example/kotlindemos/BasicMapDemoActivity.kt
Updates the BasicMapDemoActivity demo to use the KTX for the Maps SDK and coroutines, as shown at https://github.com/googlemaps/android-maps-ktx#coroutines.
=> feat: Use coroutine and AMU-KTX .awaitMap() to init basic map demo

ApiDemos/kotlin/app/src/main/java/com/example/kotlindemos/BasicMapDemoActivity.kt
Based on additional comments in https://github.com/googlemaps/android-samples/pull/188:
* Use KTX for addMarker()
* Allow optional for GoogleMap
=> chore: Update basic map demo

tutorials/java/MapWithMarker/app/src/main/java/com/example/mapwithmarker/MapsMarkerActivity.java, tutorials/kotlin/MapWithMarker/app/src/main/java/com/example/mapwithmarker/MapsMarkerActivity.kt
Adding regiontag on MapsWithMarker and not using KTX in Kotlin.
=> chore: Adding regiontag for MapsMarkerActivity

ApiDemos/java/app/build.gradle, ApiDemos/java/app/src/gms/java/com/example/mapdemo/StreetViewPanoramaOptionsDemoActivity.java, ApiDemos/java/app/src/main/res/values/strings.xml, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/DemoDetailsList.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/StreetViewPanoramaOptionsDemoActivity.kt, ApiDemos/kotlin/app/src/gms/res/layout/street_view_panorama_options_demo.xml, ApiDemos/kotlin/app/src/main/AndroidManifest.xml, ApiDemos/kotlin/app/src/main/res/values/strings.xml
* Remove redundant cast for CheckBox
* Normalize instance variable names
* Normalize capitalization of activity title in UI list
* Use lambda (requires Java 8 support)
* Support Java 8 features (for all Java demos) via build.gradle
=> chore: Add StreetViewPanoramaOptionsDemoActivity in Kotlin

ApiDemos/java/app/build.gradle, ApiDemos/java/app/src/gms/java/com/example/mapdemo/StreetViewPanoramaEventsDemoActivity.java, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/DemoDetailsList.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/StreetViewPanoramaEventsDemoActivity.kt, ApiDemos/kotlin/app/src/gms/res/layout/street_view_panorama_events_demo.xml, ApiDemos/kotlin/app/src/main/AndroidManifest.xml, ApiDemos/kotlin/app/src/main/res/values/strings.xml
* Remove redundant cast for TextView
* Use lambda (requires Java 8 support)
* Support Java 8 features (for all Java demos) via build.gradle
=> chore: Add StreetViewPanoramaEventsDemoActivity in Kotlin

ApiDemos/java/app/src/gms/java/com/example/mapdemo/StreetViewPanoramaViewDemoActivity.java, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/DemoDetailsList.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/StreetViewPanoramaViewDemoActivity.kt, ApiDemos/kotlin/app/src/main/AndroidManifest.xml, ApiDemos/kotlin/app/src/main/res/values/strings.xml
=> chore: Add StreetViewPanoramaViewDemoActivity in Kotlin

ApiDemos/java/app/src/gms/java/com/example/mapdemo/LiteDemoActivity.java, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/DemoDetailsList.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/LiteDemoActivity.kt, ApiDemos/kotlin/app/src/gms/res/layout/lite_demo.xml, ApiDemos/kotlin/app/src/main/AndroidManifest.xml, ApiDemos/kotlin/app/src/main/res/values/strings.xml
=> chore: Add LiteDemoActivity in Kotlin

ApiDemos/java/app/src/gms/java/com/example/mapdemo/EventsDemoActivity.java, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/DemoDetailsList.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/EventsDemoActivity.kt, ApiDemos/kotlin/app/src/gms/res/layout/events_demo.xml, ApiDemos/kotlin/app/src/main/AndroidManifest.xml, ApiDemos/kotlin/app/src/main/res/values/strings.xml
* Remove redundant cast for TextView
=> chore: Add EventsDemoActivity in Kotlin

ApiDemos/java/app/src/gms/java/com/example/mapdemo/IndoorDemoActivity.java, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/DemoDetailsList.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/IndoorDemoActivity.kt, ApiDemos/kotlin/app/src/gms/res/layout/indoor_demo.xml, ApiDemos/kotlin/app/src/main/AndroidManifest.xml, ApiDemos/kotlin/app/src/main/res/values/strings.xml
* Remove redundant cast for TextView
* Fix spelling in string
=> chore: Add IndoorDemoActivity in Kotlin

ApiDemos/java/app/src/gms/java/com/example/mapdemo/CameraDemoActivity.java, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/CameraDemoActivity.kt
Also made following changes to Java version:
* Remove Hungarian notation from variables
* Remove redundant view casts
This replaces the in-line code currently at:
https://developers.google.com/maps/documentation/android-sdk/events#camera_change_events
@arriolac Could you give this a close look? It's the first set of region tags I've added.
=> chore: Add region tags for CameraDemoActivity

tutorials/java/MapWithMarker/app/src/main/java/com/example/mapwithmarker/MapsMarkerActivity.java, tutorials/kotlin/MapWithMarker/app/src/main/java/com/example/mapwithmarker/MapsMarkerActivity.kt
Adding region tags in MapsMarkerActivity.
=> chore: Add region tags in MapsMarkerActivity.

ApiDemos/java/app/src/gms/java/com/example/mapdemo/CircleDemoActivity.java, ApiDemos/java/app/src/gms/java/com/example/mapdemo/PolygonDemoActivity.java, ApiDemos/java/app/src/gms/java/com/example/mapdemo/PolylineDemoActivity.java
* Remove Hungarian notation from variables
* Remove redundant view casts
=> chore: Update Circle, Polygon, and Polyline demo activities

ApiDemos/kotlin/README.md
Thank you for opening a Pull Request!
---
Fixes #<issue_number_goes_here> 🦕
=> Fix spelling

ApiDemos/kotlin/app/src/gms/AndroidManifest.xml, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/RawMapViewDemoActivity.kt
=> fix: activity added to manifest, state saving fix

ApiDemos/kotlin/app/build.gradle
Remove transitive dependencies.
=> chore: Remove transitive dependencies.

ApiDemos/java/app/build.gradle, ApiDemos/kotlin/app/build.gradle, snippets/app/build.gradle, tutorials/java/CurrentPlaceDetailsOnMap/app/build.gradle, tutorials/java/MapWithMarker/app/build.gradle, tutorials/java/Polygons/app/build.gradle, tutorials/kotlin/CurrentPlaceDetailsOnMap/app/build.gradle, tutorials/kotlin/MapWithMarker/app/build.gradle, tutorials/kotlin/Polygons/app/build.gradle
Update secrets-gradle-plugin coordinate.
=> chore: Update secrets-gradle-plugin to 1.1.0

ApiDemos/java/app/build.gradle, ApiDemos/java/build.gradle, ApiDemos/java/gradle/wrapper/gradle-wrapper.properties, ApiDemos/kotlin/app/build.gradle, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/PermissionUtils.kt, ApiDemos/kotlin/app/src/v3/java/com/example/kotlindemos/PermissionUtils.kt, ApiDemos/kotlin/build.gradle, ApiDemos/kotlin/gradle/wrapper/gradle-wrapper.properties, WearOS/Wearable/build.gradle, WearOS/build.gradle, snippets/app/build.gradle, snippets/app/src/gms/java/com/google/maps/utils/kotlin/Multilayer.kt, snippets/build.gradle, snippets/gradle/wrapper/gradle-wrapper.properties, tutorials/java/CurrentPlaceDetailsOnMap/app/build.gradle, tutorials/java/CurrentPlaceDetailsOnMap/build.gradle, tutorials/java/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties, tutorials/java/MapWithMarker/build.gradle, tutorials/java/MapWithMarker/gradle/wrapper/gradle-wrapper.properties, tutorials/java/Polygons/build.gradle, tutorials/java/Polygons/gradle/wrapper/gradle-wrapper.properties, tutorials/java/StyledMap/build.gradle, tutorials/java/StyledMap/gradle/wrapper/gradle-wrapper.properties, tutorials/kotlin/CurrentPlaceDetailsOnMap/app/build.gradle, tutorials/kotlin/CurrentPlaceDetailsOnMap/build.gradle, tutorials/kotlin/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties, tutorials/kotlin/MapWithMarker/build.gradle, tutorials/kotlin/MapWithMarker/gradle/wrapper/gradle-wrapper.properties, tutorials/kotlin/Polygons/build.gradle, tutorials/kotlin/Polygons/gradle/wrapper/gradle-wrapper.properties
=> chore: Update dependencies and remove jcenter()

.github/workflows/build.yml, .gitignore, ApiDemos/java/build.gradle, ApiDemos/java/gradle.properties, ApiDemos/java/gradle/wrapper/gradle-wrapper.properties, ApiDemos/kotlin/app/build.gradle, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/CircleDemoActivity.kt, ApiDemos/kotlin/app/src/gms/res/layout/activity_circle_demo.xml, ApiDemos/kotlin/app/src/v3/java/com/example/kotlindemos/CircleDemoActivity.kt, ApiDemos/kotlin/app/src/v3/res/layout/activity_circle_demo.xml, ApiDemos/kotlin/build.gradle, ApiDemos/kotlin/gradle/wrapper/gradle-wrapper.properties, snippets/build.gradle, snippets/gradle/wrapper/gradle-wrapper.properties, tutorials/java/CurrentPlaceDetailsOnMap/build.gradle, tutorials/java/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties, tutorials/java/MapWithMarker/build.gradle, tutorials/java/MapWithMarker/gradle/wrapper/gradle-wrapper.properties, tutorials/java/Polygons/build.gradle, tutorials/java/Polygons/gradle/wrapper/gradle-wrapper.properties, tutorials/java/StyledMap/build.gradle, tutorials/java/StyledMap/gradle/wrapper/gradle-wrapper.properties, tutorials/kotlin/CurrentPlaceDetailsOnMap/build.gradle, tutorials/kotlin/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties, tutorials/kotlin/MapWithMarker/build.gradle, tutorials/kotlin/MapWithMarker/gradle/wrapper/gradle-wrapper.properties, tutorials/kotlin/Polygons/build.gradle, tutorials/kotlin/Polygons/gradle/wrapper/gradle-wrapper.properties
Updating samples to use AGP 7.0.0.
=> chore: Using AGP 7.0.0

snippets/app/src/gms/java/com/google/maps/example/MapsActivity.java, snippets/app/src/gms/java/com/google/maps/example/kotlin/MapsActivity.kt, tutorials/kotlin/CurrentPlaceDetailsOnMap/app/build.gradle, tutorials/kotlin/CurrentPlaceDetailsOnMap/app/src/main/AndroidManifest.xml, tutorials/kotlin/CurrentPlaceDetailsOnMap/app/src/main/java/com/example/currentplacedetailsonmap/MapsActivityCurrentPlace.kt
Add new region tag so the R import statement can be ignored.
=> chore: Add maps_android_mapsactivity region tag.

snippets/app/build.gradle, snippets/app/src/gms/java/com/google/maps/example/kotlin/KTX.kt
=> chore: Add KTX snippets.

snippets/app/src/gms/java/com/google/maps/example/MapId.java, snippets/app/src/gms/java/com/google/maps/example/kotlin/MapId.kt
=> chore: Add snippets for MapID.

ApiDemos/kotlin/app/build.gradle, tutorials/kotlin/CurrentPlaceDetailsOnMap/app/build.gradle, tutorials/kotlin/MapWithMarker/app/build.gradle, tutorials/kotlin/Polygons/app/build.gradle
* Remove useless kotlin-android-extensions plugin
* Use kotlin-parcelize plugin instead of kotlin-android-extensions plugin
=> fix: Remove useless deprecated kotlin-android-extensions plugin

tutorials/java/CurrentPlaceDetailsOnMap/README.md, tutorials/java/CurrentPlaceDetailsOnMap/app/build.gradle, tutorials/java/CurrentPlaceDetailsOnMap/app/src/main/AndroidManifest.xml, tutorials/java/CurrentPlaceDetailsOnMap/app/src/main/java/com/example/currentplacedetailsonmap/MapsActivityCurrentPlace.java, tutorials/java/CurrentPlaceDetailsOnMap/gradle.properties, tutorials/java/MapWithMarker/gradle.properties, tutorials/java/Polygons/app/build.gradle, tutorials/java/Polygons/app/src/main/AndroidManifest.xml, tutorials/java/StyledMap/app/build.gradle, tutorials/java/StyledMap/app/src/main/AndroidManifest.xml, tutorials/java/StyledMap/gradle.properties, tutorials/kotlin/CurrentPlaceDetailsOnMap/app/src/main/java/com/example/currentplacedetailsonmap/MapsActivityCurrentPlace.kt, tutorials/kotlin/CurrentPlaceDetailsOnMap/gradle.properties, tutorials/kotlin/MapWithMarker/app/build.gradle, tutorials/kotlin/MapWithMarker/app/src/main/AndroidManifest.xml, tutorials/kotlin/Polygons/app/build.gradle, tutorials/kotlin/Polygons/app/src/main/AndroidManifest.xml
Use local.properties + secrets-gradle-plugin instead.
=> chore: Remove API key reference in gradle.properties.

snippets/app/build.gradle, snippets/app/src/gms/java/com/google/maps/example/kotlin/MapsCompose.kt
=> chore(Snippets): Add Maps Compose snippets.

snippets/app/src/gms/java/com/google/maps/example/kotlin/MapsCompose.kt
Update snippet on https://developers.google.com/maps/documentation/android-sdk/maps-compose#add_a_map_to_your_app
=> chore(Snippet): Fix usage of setting the camera's position.

snippets/app/build.gradle, snippets/app/src/gms/java/com/google/maps/example/kotlin/MapsCompose.kt, snippets/gradle/wrapper/gradle-wrapper.properties, tutorials/java/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties, tutorials/java/MapWithMarker/gradle/wrapper/gradle-wrapper.properties, tutorials/java/Polygons/gradle/wrapper/gradle-wrapper.properties, tutorials/java/StyledMap/gradle/wrapper/gradle-wrapper.properties, tutorials/kotlin/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties, tutorials/kotlin/MapWithMarker/gradle/wrapper/gradle-wrapper.properties, tutorials/kotlin/Polygons/gradle/wrapper/gradle-wrapper.properties
=> chore: Fix build failures.

snippets/app/build.gradle, snippets/app/src/gms/java/com/google/maps/example/kotlin/MapsCompose.kt
Update snippet for Marker usage to use maps compose 2.0.0.
=> chore: Update maps compose snippet 2.0.0

snippets/app/build.gradle, snippets/build.gradle, snippets/settings.gradle
Adds the following region tags:
* maps_android_settings_dependency_resolution_management
* maps_android_settings_plugin_management
=> chore(snippets): Add region tag for dependency management.

WearOS/Wearable/build.gradle, WearOS/build.gradle, WearOS/gradle/wrapper/gradle-wrapper.properties, WearOS/settings.gradle
=> chore: Update WearOS to use latest AGP.

snippets/app/build.gradle, snippets/app/src/gms/java/com/google/maps/example/kotlin/MapsRx.kt, snippets/app/src/gms/java/com/google/maps/example/kotlin/PlacesRx.kt
Add snippets for Maps Rx library.
=> chore(snippets): Add snippets for Maps Rx.

snippets/app/build.gradle, snippets/app/src/main/AndroidManifest.xml, snippets/build.gradle
New region tags `maps_android_secrets_gradle_plugin_project_level_config` and `maps_android_secrets_gradle_plugin_config`.
=> chore: Add secrets-gradle-plugin region tags.

ApiDemos/java/gradle/wrapper/gradle-wrapper.properties, ApiDemos/kotlin/app/build.gradle, ApiDemos/kotlin/gradle/wrapper/gradle-wrapper.properties, snippets/app/build.gradle, snippets/app/src/gms/java/com/google/maps/utils/Clustering.java, snippets/app/src/gms/java/com/google/maps/utils/Multilayer.java, snippets/app/src/gms/java/com/google/maps/utils/kotlin/Clustering.kt, snippets/app/src/gms/java/com/google/maps/utils/kotlin/Multilayer.kt, snippets/build.gradle, snippets/gradle/wrapper/gradle-wrapper.properties, tutorials/java/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties, tutorials/java/MapWithMarker/gradle/wrapper/gradle-wrapper.properties, tutorials/java/Polygons/gradle/wrapper/gradle-wrapper.properties, tutorials/java/StyledMap/gradle/wrapper/gradle-wrapper.properties, tutorials/kotlin/CurrentPlaceDetailsOnMap/gradle/wrapper/gradle-wrapper.properties, tutorials/kotlin/MapWithMarker/gradle/wrapper/gradle-wrapper.properties, tutorials/kotlin/Polygons/gradle/wrapper/gradle-wrapper.properties
The following PR introduces a general update of dependencies:
- AGP updated.
- Places library updated.
- Kotlin Compiler updated (we can jump on Kotlin 1.8 without any compiler warning).
- Other dependencies updated.
---
- [] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
=> chore: update of dependencies

.github/workflows/build.yml, snippets/app/build.gradle, snippets/build.gradle, snippets/gradle/wrapper/gradle-wrapper.properties
For https://developers.google.com/maps/documentation/android-sdk/secrets-gradle-plugin
=> chore(docs): update secrets-gradle-plugin install snippets

ApiDemos/java/app/src/gms/java/com/example/mapdemo/MainActivity.java, ApiDemos/java/app/src/gms/res/layout/main.xml, ApiDemos/java/app/src/main/res/values/strings.xml, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/MainActivity.kt, ApiDemos/kotlin/app/src/gms/res/layout/activity_main.xml, ApiDemos/kotlin/app/src/main/res/values/strings.xml
The current PRs removes the renderer selection from our samples.
---
Fixes #1429 🦕
=> feat: removed renderer selection from the samples

ApiDemos/java/app/src/gms/java/com/example/mapdemo/AdvancedMarkersDemoActivity.java, ApiDemos/java/app/src/gms/java/com/example/mapdemo/EventsDemoActivity.java, ApiDemos/java/app/src/gms/java/com/example/mapdemo/MarkerDemoActivity.java, ApiDemos/java/app/src/gms/java/com/example/mapdemo/MyLocationDemoActivity.java, ApiDemos/java/app/src/gms/java/com/example/mapdemo/PolygonDemoActivity.java, ApiDemos/java/app/src/gms/java/com/example/mapdemo/PolylineDemoActivity.java, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/AdvancedMarkersDemoActivity.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/EventsDemoActivity.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/MarkerDemoActivity.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/MyLocationDemoActivity.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/PolygonDemoActivity.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/PolylineDemoActivity.kt
Tag 6 top-priority samples for new samples pages on developers.google.com
=> chore: add region tags to 6 samples

ApiDemos/java/app/src/gms/AndroidManifest.xml, ApiDemos/java/app/src/gms/java/com/example/mapdemo/DemoDetailsList.java, ApiDemos/java/app/src/gms/java/com/example/mapdemo/MainActivity.java, ApiDemos/java/app/src/gms/java/com/example/mapdemo/MapColorSchemeActivity.java, ApiDemos/java/app/src/gms/java/com/example/mapdemo/PolylineDemoActivity.java, ApiDemos/java/app/src/main/res/layout/map_color_scheme_demo.xml, ApiDemos/java/app/src/main/res/values/strings.xml, ApiDemos/kotlin/app/build.gradle, ApiDemos/kotlin/app/src/gms/AndroidManifest.xml, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/AdvancedMarkersDemoActivity.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/DemoDetailsList.kt, ApiDemos/kotlin/app/src/gms/java/com/example/kotlindemos/MapColorSchemeActivity.kt, ApiDemos/kotlin/app/src/gms/res/layout/map_color_scheme_demo.xml, ApiDemos/kotlin/app/src/main/res/values/strings.xml
The following PR adds a sample with the newly released [MapColorScheme](https://developers.google.com/maps/documentation/android-sdk/configure-map#map_color_scheme).
=> feat: added Kotlin MapColorScheme sample

.github/workflows/build.yml, .github/workflows/release.yml, ApiDemos/java/app/build.gradle, ApiDemos/kotlin/app/build.gradle, WearOS/Wearable/build.gradle, snippets/app-compose/build.gradle, snippets/app-ktx/build.gradle, snippets/app-places-ktx/build.gradle, snippets/app-rx/build.gradle, snippets/app-utils-ktx/build.gradle, snippets/app-utils/build.gradle, snippets/app/build.gradle, snippets/app/src/gms/java/com/google/maps/example/AdvancedMarkersCollisionActivity.java, snippets/app/src/gms/java/com/google/maps/example/CloudBasedMapStylingActivity.java, snippets/app/src/gms/java/com/google/maps/example/PolylineCustomizationActivity.java, snippets/app/src/gms/java/com/google/maps/example/kotlin/AdvancedMarkersCollisionActivity.kt, snippets/app/src/gms/java/com/google/maps/example/kotlin/CloudBasedMapStylingActivity.kt, snippets/app/src/gms/java/com/google/maps/example/kotlin/PolylineCustomizationActivity.kt, snippets/app/src/gms/res/values/strings.xml, tutorials/java/StyledMap/app/build.gradle, tutorials/kotlin/CurrentPlaceDetailsOnMap/app/build.gradle, tutorials/kotlin/MapWithMarker/app/build.gradle, tutorials/kotlin/Polygons/app/build.gradle
chore: the java compatibility version
Thank you for opening a Pull Request!
---
- [x ] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x ] Ensure the tests and linter pass
- [x ] Code coverage does not decrease (if any source code was changed)
- [x ] Appropriate docs were updated (if necessary)
Fixes #<issue_number_goes_here> 🦕
=> feat: copies some snippets that were in v3 only to gms
